db:
  image: mysql:5.6
  environment:
    - MYSQL_DATABASE=mapknitter
    - MYSQL_USER=mapknitter
    - MYSQL_PASSWORD=mapknitter
    - MYSQL_RANDOM_ROOT_PASSWORD=true
  volumes:
    - /srv/mapknitter_priv1/mk1_database:/var/lib/mysql
web:
  build: .
  command: ./start.sh
  environment:
    - RAILS_ENV=production
  volumes:
    - ./:/app
  ports:
    - "127.0.0.1:3000:3000"
  links:
    - db
